Add right-text-indent and right-last-line-indent to API
mtmse/dotify.api pull request #12
Opened 2020-06-04 16:58 UTC by bertfrees

2020-06-05 05:06 UTC, kalaspuffar requested changes

2020-06-05 05:06 UTC, kalaspuffar commented on src/org/daisy/dotify/api/formatter/TextBlockProperties.java
> +	 * Get rught text indent, in characters
rught -> right

2020-06-05 15:07 UTC, PaulRambags approved these changes

2020-06-05 15:09 UTC, PaulRambags commented
I have already approved (although @bertfrees needs to apply a minor change as indicated by @kalaspuffar).

2020-06-05 18:12 UTC, bertfrees commented on src/org/daisy/dotify/api/formatter/TextBlockProperties.java
> +	 * Get rught text indent, in characters
Done

2020-06-09 05:57 UTC, kalaspuffar approved these changes

2020-06-09 05:57 UTC, merged